# Generated by Django 4.2.5 on 2023-09-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_subscriber_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
