# Generated by Django 4.2.5 on 2023-09-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_subscriber_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='is_active',
        ),
    ]
